---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

#read in and clean the data set a bit
set.seed(1)
data(rest_inspec)

inspec = 
  rest_inspec %>% 
  janitor::clean_names() %>% 
  select(
    dba, boro, zipcode, cuisine = cuisine_description, critical_flag, score, grade, inspection_date, grade_date
  ) %>%
  filter(
    grade %in% c("A", "B", "C"),
    cuisine != "Not Listed/Not Applicable") %>% 
  sample_n(5000) %>% 
  mutate(cuisine = recode(cuisine, 
                          "Café/Coffee/Tea" = "Cafe/Tea",
                          "Latin (Cuban, Dominican, Puerto Rican, South & Central American)" = "Latin",
                          "Bottled beverages, including water, sodas, juices, etc." = "Bottled Beverages",
                          "Ice Cream, Gelato, Yogurt, Ices" = "Ice Cream",
                          "Juice, Smoothies, Fruit Salads" = "Juice/Salads",
                          "Vietnamese/Cambodian/Malaysia" = "Other East Asian",
                          "Sandwiches/Salads/Mixed Buffet" = "Sandwiches/Salads"))
```



### Frame 1

```{r}
inspec %>% 
  mutate(boro = fct_reorder(boro, score)) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box",
          colors = "Set3")
```   
    
### Frame 2

```{r}
ax_1 <- list(
  title = "",
  tickangle = 40,
  showticklabels = TRUE)

ax_2 <- list(
  title = "",
  showticklabels = TRUE)

inspec %>% 
  select(grade, score, grade_date) %>% 
  separate(grade_date, into = c("year", "month"), convert = TRUE) %>%
  mutate(
    month = factor(month.abb[month], levels = month.abb),
    month_1 = month,
    year_1 = year - 2000) %>% 
  group_by(year_1, month_1, grade, year, month) %>% 
  summarise(med_score = round(median(score, na.rm = TRUE),1)) %>% 
  unite("time", "year_1":"month_1", sep = "-", remove = TRUE, na.rm = FALSE) %>% 
  ungroup() %>% 
  arrange(year, month) %>% 
  mutate(time = factor(time, levels = unique(time))) %>% 
  arrange(time) %>% 
  plot_ly(x = ~time, y = ~med_score, group = ~grade,
          type = "scatter", 
          color = ~grade, 
          mode = "lines+markers",
          text = ~ paste(
      "Time: ", year, month,
      "<br>Median Score: ", med_score),
    hoverinfo = "text") %>%
    layout(xaxis = ax_1, yaxis = ax_2)
  
```

   
### Frame 3

```{r}
  inspec %>%
  select(boro, cuisine, score) %>% 
  group_by(boro, cuisine) %>% 
  summarise(median_score = round(median(score, na.rm = TRUE),1)) %>% 
  arrange(desc(cuisine)) %>% 
  plot_ly(
    x = ~cuisine, y = ~boro,
    height = 400, width = 1400) %>%
  add_heatmap(
    z = ~median_score,
    text = ~paste(
      "Boro: ", boro, "<br>Cuisine: ", cuisine,
      "<br>Median Score: ", median_score),
    hoverinfo = "text", showscale = TRUE,
    opacity = 0.90) %>%
    layout(xaxis = ax_1, yaxis = ax_2)
```

