---
title: "Plotly Examples"
output: 
  html_document:
    code_folding: hide
  toc: true
  toc_float: true
---


Websites _with interactive graphics_


```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```


```{r} 
#clean the data set a bit
set.seed(10)

data(rest_inspec)

inspec = 
  rest_inspec %>% 
  janitor::clean_names() %>% 
  select(
    dba, boro, zipcode, cuisine = cuisine_description, critical_flag, score, grade, inspection_date, grade_date
  ) %>%
  filter(
    !is.na(grade), grade != "Not Yet Graded") %>% 
  sample_n(5000)
```

```{r}
inspec %>% 
  mutate(boro = fct_reorder(boro, score)) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box",
          colors = "Set2")
```



Making an interactive scatterplot:
```{r}
nyc_airbnb %>% 
  plot_ly(x = ~lat, y = ~long, type = "scatter", mode = "markers",
          color = ~price, alpha = 0.5) #type -> what kind of plot; mode -> don't connect the dots; ~ means that is the variable to be used for x/y axis

```

Make Boxplot:
```{r}
common_neighborhoods =
  nyc_airbnb %>% 
  count(neighbourhood, sort = TRUE) %>% 
  top_n(8) %>% 
  select(neighbourhood)

inner_join(nyc_airbnb, common_neighborhoods, by = "neighbourhood") %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% #put everthing in increasing order based on price;
    plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")

```


Make a barchart
```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% #reorder by n;
  plot_ly(x = ~neighbourhood, y = ~n, type = "bar", color = ~neighbourhood)


```

